var chrome=window.chrome||{},drawAddPageToWhiteListDialog=window.drawAddPageToWhiteListDialog||{};
let DEBUG=!1,debugPerformance=!1,urlParamChache={},backProcessed=!1,title,favicon,link,secondTime=!1,restoreEvent="hover",reloadTabOnRestore=!1,tabIconOpacityChange=!1,tabIconStatusVisualize=!1,tabId,targetUrl,bgScreen=null,screenshotDevicePixelRatio,isTabMarkedForUnsuspend=!1,parkedUrl,screenPromise,faviconDrawed,loaded=new Promise(a=>{window.addEventListener("load",()=>{debugPerformance&&console.log("onload: ",Date.now());a()})}),DOMContentLoaded;
window.domLoadedPromise=new Promise(a=>{document.addEventListener("DOMContentLoaded",()=>{if(!DOMContentLoaded){DOMContentLoaded=!0;debugPerformance&&console.log("onDOMContentLoaded: ",Date.now());try{createTitleAndIcon(),applysUserDisplayHeight(window.innerHeight)}catch(c){}a()}},!0)});debugPerformance&&console.log("getBackgroundPage: ",Date.now());
try{chrome.runtime.getBackgroundPage(a=>{debugPerformance&&console.log("getBackgroundPage Loaded: ",Date.now());tabId=parseUrlParam("tabId");screenPromise=new Promise(c=>{a.getScreen(tabId,parseUrlParam("sessionId"),(b,d)=>{c({scr:b,pixRat:d})})});window.domLoadedPromise.then(()=>{function c(){debugPerformance&&console.log("Continue Chaeck: ",Date.now());chrome.tabs.getCurrent(b=>{parkedUrl=a.getTabInfo(b).parkedUrl});isTabMarkedForUnsuspend=a.isTabMarkedForUnsuspend(tabId,parseUrlParam("sessionId"),
{remove:!0});DEBUG&&console.log("isTabMarkedForUnsuspend: ",isTabMarkedForUnsuspend);isTabMarkedForUnsuspend?(document.getElementById("resoteImg").style.display="none",document.getElementById("topRestore").style.display="none",reloadTabOnRestore=a.getReloadTabOnRestore(),setTimeout(continueStart,0)):(debugPerformance&&console.log("Get Screen: ",Date.now()),tabIconStatusVisualize=a.getTabIconStatusVisualize(),tabIconOpacityChange=a.getTabIconOpacityChange(),screenPromise.then(({scr:b,pixRat:d})=>{try{debugPerformance&&
console.log("Get Screen Loaded: ",Date.now());if(null==b)throw Error("Screen image is null!");bgScreen=b;screenshotDevicePixelRatio=d?d:window.devicePixelRatio;setTimeout(()=>{drawContent(a)},0);setTimeout(continueStart,0)}catch(e){console.error(e),setTimeout(()=>{drawContent(a)},0),setTimeout(continueStart,0)}}),debugPerformance&&console.log("Apply background: ",Date.now()),applysSreenshotCssStyle(a.getScreenshotCssStyle()),restoreEvent=a.getRestoreEvent(),reloadTabOnRestore=a.getReloadTabOnRestore(),
createTitleAndIcon(!0))}try{let b=a.getStartDiscarted();DEBUG&&console.log("bgpage.getStartDiscarted(): ",b);1==b?15E3>Date.now()-a.getStartedAt()?(DEBUG&&console.log("(new Date().getTime() - bgpage.getStartedAt()) < 15000: ",15E3>Date.now()-a.getStartedAt()),a.isFirstTimeTabDiscard(tabId)?(DEBUG&&console.log("bgpage.isFirstTimeTabDiscard(tabId): ",a.isFirstTimeTabDiscard(tabId)),chrome.tabs.getCurrent(d=>{!1===d.active?(DEBUG&&console.log("tab.active: ",d.active),window.stop(),chrome.runtime.sendMessage({method:"[AutomaticTabCleaner:DiscardTab]"})):
c()})):c()):c():c()}catch(b){console.error(b),applyRestoreButtonView(a),drawContent(a),setTimeout(continueStart,0)}});window.domLoadedPromise=null})}catch(a){console.error(a),window.domLoadedPromise.then(()=>{applyRestoreButtonView();setTimeout(drawContent,0);setTimeout(continueStart,0)})}
function applysUserDisplayHeight(a){let c=document.getElementById("resoteImg");DEBUG&&console.log("DisplayHeight: ",a);null!=a&&(600>=a?(c.width="128",c.height="128",c.classList.add("h600")):800>=a?(c.width="160",c.height="160",c.classList.add("h800")):1024>=a&&(c.width="196",c.height="196",c.classList.add("h1024")));c.classList.remove("wait-for-render")}
function applyRestoreButtonView(a,c){c=c?c:a?a.getRestoreButtonView():null;let b=document.getElementById("screen"),d=document.getElementById("resoteImg");a=()=>{document.body.classList.add("always-visible");document.getElementById("nativeUrlSpan").onclick=()=>{window.getSelection().selectAllChildren(document.getElementById("nativeUrlSpan"))}};null==c||"roundIcon"===c?(d.style.display="block",d.style.opacity=null,document.getElementById("topRestore").style.display="none",a(),d.onmouseover=()=>{"hover"===
restoreEvent&&(goBack(),d.className="restore inprogress",b.classList.add("inprogress"))},d.onclick=()=>{"click"===restoreEvent&&(goBack(),d.className="restore inprogress",b.classList.add("inprogress"))}):"topBar"===c?(d.style.display="none",document.getElementById("topRestore").style.display="block",document.getElementById("topRestore").onclick=()=>{goBack();document.getElementById("topRestore").className="topRestore inprogress";b.classList.add("inprogress")}):"noIcon"===c&&(d.style.display="none",
document.getElementById("topRestore").style.display="none",a());document.getElementById("screenDiv").onclick=()=>{goBack();d.className="restore inprogress";b.classList.add("inprogress")}}function applyBackground(a){document.body.style.background=a}function applysSreenshotCssStyle(a){const c=document.getElementById("screen");c.style.cssText=a;applyPixelRatio(c)}
function createTitleAndIcon(a){DEBUG&&console.log("createTitleAndIcon...");!faviconDrawed&&(null==title&&(title=parseUrlParam("title")),document.title!==title&&(document.title=title),link=document.getElementById("faviconLink"),null==link||a||null==link.href||-1!==link.href.indexOf("img/icon16_off.png"))&&(null==link&&(link=document.createElement("link"),link.type="image/x-icon",link.rel="shortcut icon"),null==favicon||a?(generateFaviconUri(parseUrlParam("icon",!1),c=>{favicon=c;link.href=c;"faviconLink"!==
link.id&&(link.id="faviconLink",document.getElementsByTagName("head")[0].appendChild(link))}),faviconDrawed=!0):null!=favicon&&(link.href=favicon))}function parseUrlParam(a,c){var b;if(null!=(b=urlParamChache[a]))return b;let d=window.location.search.substr(1).split("&");for(let e=0;e<d.length;e++)if(b=d[e].split("="),b[0]===a)return!0===c?decodeURIComponent(b[1]):urlParamChache[a]=decodeURIComponent(b[1])}
function generateFaviconUri(a,c){DEBUG&&console.log("generateFaviconUri...");let b=new Image,d=setTimeout(()=>{b.onerror()},3E3);b.onload=()=>{clearTimeout(d);let e,g;e=window.document.createElement("canvas");e.width=b.width;e.height=b.height;g=e.getContext("2d");g.globalAlpha=tabIconOpacityChange?.65:1;g.drawImage(b,0,0);DEBUG&&console.log("tabIconStatusVisualize: "+tabIconStatusVisualize);tabIconStatusVisualize?drawWaterMark(e,g,b.width,c):c(e.toDataURL())};b.onerror=e=>{clearTimeout(d);console.log("Loading Favicon Error",
e);b.src=chrome.extension.getURL("img/new_page.png")};b.src=a&&"undefined"!=a?a:chrome.extension.getURL("img/new_page.png")}function drawWaterMark(a,c,b,d){DEBUG&&console.log("drawWaterMark...");let e=new Image;64!==b?(console.error("Unexpected: Favicon image != 64x64 -> "+b),d(a.toDataURL())):(e.onload=()=>{c.globalAlpha=.95;c.drawImage(e,49,49);d(a.toDataURL())},e.src="img/watermark/Circle_Blue_16_Brite_100.png")}
function cssScale(){return"scale("+1/screenshotDevicePixelRatio+", "+1/screenshotDevicePixelRatio+")"}function applyPixelRatio(a){try{DEBUG&&console.log("screenshotDevicePixelRatio: ",screenshotDevicePixelRatio),1<screenshotDevicePixelRatio&&(a.style.transform=cssScale())}catch(c){console.error(c)}}
function drawContent(a){debugPerformance&&console.log("Drow Content: ",Date.now());let c=document.getElementById("screen");c.onload=()=>{applyRestoreButtonView(a);applyBackground("#"+a.getParkBgColor())};c.onerror=()=>{applyRestoreButtonView(a);applyBackground("#"+a.getParkBgColor())};applyPixelRatio(c);null==bgScreen?(c.style.display="none",document.getElementById("title").innerHTML=title,document.getElementById("title").href=parseUrlParam("url"),document.getElementById("favicon").src=favicon,document.getElementById("title_div").style.display=
"block",document.getElementById("nativeUrl").classList.add("visible"),c.onerror()):c.src=bgScreen;favicon=bgScreen=null;debugPerformance&&(console.log("Complete!!!: ",Date.now()),console.timeEnd("Load time..."))}function continueStart(){isTabMarkedForUnsuspend?(DEBUG&&console.log("Prepare to go Back!"),goBack({force:!0})):(DEBUG&&console.log("Waiting for Page load...",Date.now()),loaded.then(()=>{DEBUG&&console.log("Page Already loaded");startEX()}))}
function startEX(){debugPerformance&&console.log("Start begun...!",Date.now());favicon=null;chrome.runtime.onMessage.addListener(d=>{"[AutomaticTabCleaner:RestoreMessage]"===d.method?d.anyWay?goBack():chrome.tabs.getCurrent(e=>{d.tab.id==e.id&&goBack()}):"[AutomaticTabCleaner:UpdateTabsSettings]"===d.method?loaded.then(()=>{null!=d.restoreEvent&&(restoreEvent=d.restoreEvent);null!=d.reloadTabOnRestore&&(reloadTabOnRestore=d.reloadTabOnRestore);null!=d.parkBgColor&&applyBackground("#"+d.parkBgColor);
null!=d.screenshotCssStyle&&applysSreenshotCssStyle(d.screenshotCssStyle);null!=d.restoreButtonView&&applyRestoreButtonView(null,d.restoreButtonView);null!=d.tabIconStatusVisualize&&(tabIconStatusVisualize=d.tabIconStatusVisualize,createTitleAndIcon(!0))}):"[AutomaticTabCleaner:DrawAddPageToWhiteListDialog]"===d.method?drawAddPageToWhiteListDialog():"[AutomaticTabCleaner:hideDialogRequetToTab]"===d.method&&(document.getElementById("ATCSDialogiFrame").parentElement.removeChild(document.getElementById("ATCSDialogiFrame")),
document.getElementById("screen").style.filter="",window.focus(),d.options&&d.options.goBack?goBack():showNativeUrl())});secondTime=isSecondTime();document.getElementById("title").onclick=document.getElementById("titleImg").onclick=()=>{goBack();return!1};let a=parseUrlParam("url"),c=parseUrlParam("title");0===a.indexOf("http://")&&(a=a.substr(7));0===a.indexOf("https://")&&(a=a.substr(8));const b=document.getElementById("nativeUrlSpan");b.innerText=a;b.title=`Title: "${c}"`;initNativeUrlAnimation()}
function goBack(a){chrome.runtime.sendMessage({method:"[AutomaticTabCleaner:TabUnsuspended]",targetTabId:tabId,url:targetUrl});if(!backProcessed||null!=a&&!0===a.force)!1!==reloadTabOnRestore||isFromHistory()||null==parkedUrl?(DEBUG&&console.log("Reload"),window.location.replace(parseUrlParam("url"))):(DEBUG&&console.log("Back"),historyFallback(parseUrlParam("url")));backProcessed=!0}
function historyFallback(a){let c=!1;window.onbeforeunload=()=>{c=!0};window.history.go(-1);DEBUG&&setInterval(()=>{console.log("hasHistory: "+c)},100);setTimeout(()=>{1!=c&&(window.location.assign(a),DEBUG&&console.log("Force Back 500ms!!!"))},500)}window.startEX=startEX;function isSecondTime(){let a=window.location.href.lastIndexOf("#");return-1!=a&&"#secondTime"==location.href.substring(a)?!0:!1}
function isFromHistory(){let a=window.location.href.lastIndexOf("#");return-1!=a&&"#fromHistory"==location.href.substring(a)?!0:!1}let nativeUrlVisible=!1,nativeUrlTimer=null,nativeUrlTimerClose=null,nativeUrlTimerCloseAfterTimeout=null,nativeUrlPosition,nativeUrlElement=document.getElementById("nativeUrl"),nativeUrlElementHover=!1,showNativeUrl,hideNativeUrl;
function initNativeUrlAnimation(){if(null==nativeUrlElement){var a=document.getElementById("nativeUrl");if(null!=a){a.onmouseover=()=>{nativeUrlElementHover=!0;nativeUrlTimerCloseAfterTimeout&&clearTimeout(nativeUrlTimerCloseAfterTimeout)};a.onmouseout=b=>{if(b&&(b=b.toElement||b.relatedTarget)&&(b.parentNode==this||null!=b.parentNode&&b.parentNode.parentNode==this||b==this))return;nativeUrlElementHover=!1;nativeUrlTimerCloseAfterTimeout&&clearTimeout(nativeUrlTimerCloseAfterTimeout);nativeUrlTimerCloseAfterTimeout=
setTimeout(()=>{hideNativeUrl()},5E3)};hideNativeUrl=()=>{1==nativeUrlVisible&&(nativeUrlTimer=null,nativeUrlTimerClose=setInterval(()=>{a.style.top=--nativeUrlPosition+"px";-27>=nativeUrlPosition&&(nativeUrlVisible=!1,clearInterval(nativeUrlTimerClose),nativeUrlTimerClose=null)},10))};showNativeUrl=b=>{b&&b.permanent||clearTimeout(nativeUrlTimerCloseAfterTimeout);nativeUrlTimerCloseAfterTimeout=null;b&&b.permanent||hideNativeUrl();1!=nativeUrlVisible&&null==nativeUrlTimer&&(window.getSelection().selectAllChildren(document.getElementById("nativeUrlSpan")),
nativeUrlPosition=-27,nativeUrlTimer=setInterval(()=>{a.style.top=++nativeUrlPosition+"px";0<=nativeUrlPosition&&(nativeUrlVisible=!0,clearInterval(nativeUrlTimer),nativeUrlTimerCloseAfterTimeout&&clearTimeout(nativeUrlTimerCloseAfterTimeout),b&&b.permanent||(nativeUrlTimerCloseAfterTimeout=setTimeout(()=>{nativeUrlElementHover||hideNativeUrl()},5E3)))},9))};document.getElementById("nativeUrlButton").onclick=showNativeUrl;var c=(b,d)=>new Promise((e,g)=>{let f;"js"===d?(f=document.createElement("script"),
f.setAttribute("type","text/javascript"),f.setAttribute("src",b),f.onload=()=>{e()}):"css"===d&&(f=document.createElement("link"),f.setAttribute("rel","stylesheet"),f.setAttribute("type","text/css"),f.setAttribute("href",b),f.onload=()=>{e()});"undefined"!=typeof f?document.getElementsByTagName("head")[0].appendChild(f):g()});document.getElementById("pauseIcon").onclick=()=>{Promise.all([c("utils.js","js")]).then(()=>{const b=window.isDarkMode(),d=document.createElement("div"),e=document.createElement("div");
e.style.cssText="position: fixed;\n\t\t\t\ttop: 0%;\n\t\t\t\tleft: 0%;\n\t\t\t\twidth: 100%;\n\t\t\t\theight: 100%;\n\t\t\t\tbackground-color: #555;\n\t\t\t\tz-index: 1000;\n\t\t\t\topacity: .40;";const g=document.createElement("div");b&&g.classList.add("blackThemeInner");g.style.cssText="border-radius: 10px;\n\t\t\t\toverflow: hidden;\n\t\t\t\tbackground-color: #fff";const f=document.createElement("iframe");f.src="./popup.html?showSessions=no";f.style.cssText="border: 0px;\n\t\t\t\twidth: 300px;\n\t\t\t\theight: 423px;";
g.appendChild(f);b&&d.classList.add("blackTheme");d.classList.add("mainMenuDiv");d.style.cssText="position: absolute;\n\t\t\t\tz-index: 1001;\n\t\t\t\ttop: 47px;\n\t\t\t\tleft: 25px;\n\t\t\t\theight: 100%;\n\t\t\t\twidth: 300px;\n\t\t\t\t/*border-radius: 10px;\n\t\t\t\toverflow: hidden;*/";d.appendChild(g);document.body.classList.add("blur");document.body.parentElement.appendChild(d);document.body.parentElement.appendChild(e);e.onclick=()=>{d.parentElement.removeChild(d);e.parentElement.removeChild(e);
document.body.classList.remove("blur")}})};document.getElementById("settingsBtn").onclick=()=>{"none"===document.getElementById("options").style.display?(document.getElementById("options").style.display="block",Promise.all([c("lib/coloris/coloris.min.js","js"),c("lib/coloris/coloris.min.css","css"),c("part-options.css","css")]).then(()=>{chrome.runtime.getBackgroundPage(b=>{const d="roundIcon"===b.getRestoreButtonView();document.getElementById("showCircleInput").checked=d;document.getElementById("showCircleInput").onchange=
()=>{const e=document.getElementById("showCircleInput").checked?"roundIcon":"noIcon";chrome.extension.sendMessage({method:"[AutomaticTabCleaner:updateTimeout]",restoreButtonView:e})};document.getElementById("colorisInput").value="#"+b.getParkBgColor();Coloris({el:".coloris"});document.getElementById("colorisInput").oninput=()=>{const e=document.getElementById("colorisInput").value.split("#");1<=e.length&&chrome.extension.sendMessage({method:"[AutomaticTabCleaner:updateTimeout]",parkBgColor:e[1]})};
document.getElementById("allSettings").onclick=()=>{chrome.extension.sendMessage({method:"[AutomaticTabCleaner:OpenSettingsPage]"})}})})):document.getElementById("options").style.display="none"}}}}
window.drawAddPageToWhiteListDialog=()=>{if(!document.getElementById("ATCSDialogiFrame")){showNativeUrl({permanent:!0});document.getElementById("screen").style.filter="blur(1px)";var a=document.createElement("iframe");a.id="ATCSDialogiFrame";a.src=chrome.extension.getURL("dialog.html?dialog=page&url="+parseUrlParam("url"));a.style.position="fixed";a.style.top="0px";a.style.left="0px";a.style.width="100%";a.style.height="100%";a.style.zIndex=1E7;a.frameBorder=0;document.getElementsByTagName("body")[0].appendChild(a)}};
